### ISSUE TITLE
Unable to post to private channels

### ISSUE THREAD

**Issue by tgladding** [vektorlab/slackcat#1]
I'm up and running with a bot account that is able to post to public channels, that's fine.

I invited the bot to a private channel, but when I try and post to it an error is returned:

    $ slackcat -c junk demo.gif        
    slackcat Slack API error:
    No such channel.

    $ slackcat -v
    slackcat version 0.3
    $ uname -a
    Linux <host> 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bcicen** [comment]
Thanks for the feedback @tgladding! I've pushed https://github.com/vektorlab/slackcat/commit/095fc909918dcc17905208538afdf918157747d5 to add private group support and it's available now in the latest release.

**Comment by bcicen** [comment]
fixed in v0.4

**Comment by tgladding** [comment]
Thanks - works great :)
