### ISSUE TITLE
Post to direct message?

### ISSUE THREAD

**Issue by aimless55** [vektorlab/slackcat#10]
Can I use this to post a file into a direct message, or does it only work for channels?

**Comment by bcicen** [comment]
Currently you can only post to channels and private groups. I'll leave this open to track adding support for direct message though.

**Comment by toejough** [comment]
:+1:

**Comment by bcicen** [comment]
Posting to direct message added in [latest release](https://github.com/vektorlab/slackcat/releases/tag/v0.8)

**Comment by toejough** [comment]
Is there a new flag to use this feature?  I tried just substituting a user name for the channel, but got "missing_scope":

```
echo "testing..." | ~/Downloads/slackcat-0.8-darwin-amd64 -c username
missing_scope
slackcat Slack API Error: No such channel, group, or im
```

I tried `@username` and `'@username'`, too, same error.  Messaging channels still works fine.

**Comment by bcicen** [comment]
@toejough -- there is no specific flag, but the feature does require a new permission scope(users:read) to work. You should be able to enable this by re-generating a new token with `--configure`.

**Comment by bcicen** [comment]
Great! Glad you're enjoying it :)

**Comment by dmil** [comment]
Not quite working for me, has this feature been disabled?

I'm also getting

```
slackcat connected to DPI-691M as dhrumil.mehta
slackcat No such channel, group, or im
```
I know the username is spelled correctly, and I'm on `slackcat version 1.4, build`

Thanks.

**Comment by bcicen** [comment]
@dmil can you verify the username you're using matches what's shown in the output of `slackcat --list`?
