### ISSUE TITLE
Add support for multiple Slack teams

### ISSUE THREAD

**Issue by jziggas** [vektorlab/slackcat#13]
How does this work if you are logged into multiple Slacks?

**Comment by xalep** [comment]
Currently it doesn't. You would need to change the config file format, and add a `--team` argument.

**Comment by shakerlxxv** [comment]
+1

**Comment by bcicen** [comment]
Multiple Slack teams via a single config file is planned for the next release

**Comment by bcicen** [comment]
[Advanced configuration options](https://github.com/vektorlab/slackcat/blob/master/docs/configuration-guide.md) have been added in the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v0.9) to support multiple Slack teams!
