### ISSUE TITLE
The demo doesn't need to be animated

### ISSUE THREAD

**Issue by robcross** [vektorlab/slackcat#19]
The demo is super irritating to me because the gif file resets before I can read and analyze what's going on. I know it looks cool to have an animated demo, but for something as basic as this, it really doesn't have to be animated. It would be much more readable if it were just using github code styling.

Alternatively, can you just make the gif not loop? That way there's a bit of "cool animation" when a user first opens the page, but it doesn't immediately clear away.

**Comment by bcicen** [comment]
Makes sense to me. Removed loop from demo in https://github.com/vektorlab/slackcat/commit/b6034933789ef631c2caf8a7f463e812a1e4291a. Thanks for the feedback!

**Comment by robcross** [comment]
Awesome :)
