### ISSUE TITLE
CLI argument to post as preformatted text

### ISSUE THREAD

**Issue by max-arnold** [vektorlab/slackcat#20]
Sometimes it is useful to post some text as preformatted block: \`\`\`pre\`\`\`. It would be nice to have a `--pre` switch for it.

**Comment by bcicen** [comment]
Thanks for the feedback @max-arnold. The [latest release](https://github.com/vektorlab/slackcat/releases/tag/v0.8) now utilizes preformatted blocks via the --stream option.

**Comment by max-arnold** [comment]
Thanks a lot!
