### ISSUE TITLE
Set default channel in configuration

### ISSUE THREAD

**Issue by stevedesmond-ca** [vektorlab/slackcat#24]
So you don't need to specify it every time

**Comment by stevedesmond-ca** [comment]
I'll see if I can do this myself, unless someone else wants to pick it up

**Comment by bcicen** [comment]
Definitely a useful feature. Support for multiple teams in config is also in the works for the next release(https://github.com/vektorlab/slackcat/issues/13). Perhaps we should include the option to configure a default channel for each team?

**Comment by stevedesmond-ca** [comment]
I'm probably going to jump on this in the next day or so, if you haven't gotten started yet.

At least for the immediate term, I was just going to add a second line to the .slackcat file.

Not sure if that's good for now, or if more thought should be had around config file format and looking in conjunction at #13.

**Comment by bcicen** [comment]
@stevedesmond-ca default channel is now available in the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v0.9). You will need to update your config file to the "multiple teams" format described [here](https://github.com/vektorlab/slackcat/blob/master/docs/configuration-guide.md)

**Comment by stevedesmond-ca** [comment]
Confirmed -- thanks!
