### ISSUE TITLE
Invalid option, --plain

### ISSUE THREAD

**Issue by gwbarrett** [vektorlab/slackcat#26]
I tried using the --plain option (or -p), but I get an incorrect usage message.

**Comment by bcicen** [comment]
What version of Slackcat? `--plain` is only available in the latest release(v0.9).

**Comment by gwbarrett** [comment]
I just installed the latest from Homebrew, 0.8.  I guess it is behind.

On Fri, Jan 22, 2016 at 1:35 PM bradley <notifications@github.com> wrote:

> What version of Slackcat? --plain is only available in the latest
> release(v0.9).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vektorlab/slackcat/issues/26#issuecomment-174004054>.
>
-- 

—
Greg Barrett
gregory.w.barrett@gmail.com

**Comment by bcicen** [comment]
Not too far behind, 0.9 is less than a day old :)

Latest version should be available via Homebrew [soon](https://github.com/Homebrew/homebrew/pull/48381)
