### ISSUE TITLE
[Feature request] snippet language option

### ISSUE THREAD

**Issue by shawninder** [vektorlab/slackcat#29]
If I'm posting a javascript snippet to slack, it would be nice to be able to `--syntax js` or something like that to obtain the correct syntax highlighting.

**Comment by bcicen** [comment]
By default, Slack will auto-detect the snippet syntax based on the filename. Have you tried posting with `--filename snippet.js`?

**Comment by shawninder** [comment]
yes, I mean in the cases where auto-detection is wrong (partial files, badly named files, raw strings...)

**Comment by bcicen** [comment]
Makes sense. Added in #31 and will be included in the next release.
