### ISSUE TITLE
[Feature request] snippet comment option

### ISSUE THREAD

**Issue by shawninder** [vektorlab/slackcat#30]
When posting a snippet on slack, I can usually add a comment, but I don't see any `--comment` option here in slackcat. This is something I would definitely use. Perhaps others feel the same way?

**Comment by bcicen** [comment]
Added in #32; will be included in the next release.

**Comment by shawninder** [comment]
Damn, I'm really loving your quick responses @bcicen Thank you!

**Comment by bcicen** [comment]
Thank you for the feature suggestion :)
