### ISSUE TITLE
slackcat --help

### ISSUE THREAD

**Issue by dataf3l** [vektorlab/slackcat#35]
when I run slackcat --help before I configure, I get an error, not the help message.
for new users, I think it makes sense for the --help message to be visible even before configuration is available, just a suggestion though.

**Comment by bcicen** [comment]
I'm not able to replicate this in the latest version; `--help` message displays without error when no config file is present. Can you specify your platform and version?

**Comment by dataf3l** [comment]
My platform osx 10.9

**Comment by bcicen** [comment]
I'm still unable to replicate this with the latest version of slackcat; closing for now
