### ISSUE TITLE
Unable to configure on headless system

### ISSUE THREAD

**Issue by philipsd6** [vektorlab/slackcat#36]
Running on a headless system with only the `links` text browser available:
```console
$ slackcat --configure
slackcat Creating token request for Slackcat
```
But no browser pops up, no URL returned to visit manually on my workstation, so I'm unable to complete the OAuth process.

**Comment by bcicen** [comment]
Thanks for the feedback @philipsd6. `xdg-open` is used in attempting to open the OAuth URL in a browser; however, it should print the URL as a fallback.

Can you try `xdg-open http://slackcat.chat` from the same system and post the result?

**Comment by philipsd6** [comment]
```console
$ xdg-open http://slackcat.chat
```
That command launches the website via `links2` on my system, as expected.

**Comment by bcicen** [comment]
Thanks, I was able to replicate as well. Aside from running within a subprocess, I'm not sure there's any way to leverage a text-browser during the configuration process.

I've updated the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v1.1) to always output the OAuth url, regardless of `xdg-open` exit code.
