### ISSUE TITLE
'plain' flag requires 'stream’ mode

### ISSUE THREAD

**Issue by ghazel** [vektorlab/slackcat#37]
Since plain flag requires stream mode, why not enable it automatically?

**Comment by fahimsakri** [comment]
i am also facing the same issue..

**Comment by bcicen** [comment]
Removed `--plain` flag in https://github.com/vektorlab/slackcat/commit/a61ddc19c1f5e9c08ba7178066ac831ec5ec2257, making this the default behavior with `--stream` for the next release
