### ISSUE TITLE
Honor XDG_CONFIG_HOME / XDG spec

### ISSUE THREAD

**Issue by derimagia** [vektorlab/slackcat#39]
Would be nice if the config file wasn't hardcoded and it supported the XDG standards - https://wiki.archlinux.org/index.php/XDG_Base_Directory_support https://specifications.freedesktop.org/basedir-spec/latest/

Probably should default it to something like $XDG_CONFIG_HOME/slackcat/config if  XDG_CONFIG_HOME exists. Better support would set the config file to use xdg if any of the XDG_* variables exist and default XDG_CONFIG_HOME to $HOME/.config as per the standard, falling back to $HOME/.slackcat all together but I think just honoring the variable is a win.

The number of applications supporting it is increasing, and at the very least i think an environment variable should exist for overwriting.

**Comment by bcicen** [comment]
Thanks for the suggestion @derimagia -- support for `XDG_CONFIG_HOME` per standard has been added [here](https://github.com/vektorlab/slackcat/blob/master/config.go#L73) and will be included with the next release

**Comment by bcicen** [comment]
XDG basedir support is now available in the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v1.2)
