### ISSUE TITLE
ctrl+c does not stop ulpload

### ISSUE THREAD

**Issue by Triztian** [vektorlab/slackcat#40]
Operating System: macOS Sierra 10.12.3
Go: go1.8 darwin/amd64
slackcat: slackcat version 1.1, build

----

If an upload has been started and on uses `ctrl+c` to stop the upload it doesn't.

**Comment by bcicen** [comment]
file upload aborting on multiple signals has been added to the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v1.2)
