### ISSUE TITLE
Failed to initialize config dir

### ISSUE THREAD

**Issue by morganestes** [vektorlab/slackcat#43]
When I try to configure with `slackcat --configure`, the script doesn't generate a config file after pasting my token into the prompt. Instead, I get `slackcat failed to initialize config dir: mkdir : no such file or directory`.

I've tried creating the file manually at `~/.config/slackcat/config`, `~/.config/slackcat`, and `~/.slackcat`, (all are listed in [the config docs](https://github.com/vektorlab/slackcat/blob/master/docs/configuration-guide.md)) but with each of those files it tells me `slackcat missing config file at`, with the location blank.

Neither `XDG_CONFIG_DIRS` nor `XDG_CONFIG_HOME` are set in my environment, but there is an existing `~/.config` directory in use by other packages.

I'm running v1.2 on MacOS 10.12.4.

**Comment by bcicen** [comment]
Thanks @morganestes; this is fixed by https://github.com/vektorlab/slackcat/pull/42 and I've created a [new release](https://github.com/vektorlab/slackcat/releases/tag/v1.2.1) with the fix included.
