### ISSUE TITLE
Not a Admin in slack how to integrate token

### ISSUE THREAD

**Issue by zorro1992** [vektorlab/slackcat#49]
I am trying to use/test slackcat and I really cannot go ahead because I am not a admin for the slack account at my workplace. Is this token mandatory ? Is there a work around because lot of people really don't have admin access in slack and it becomes really hard to even test slackcat .

**Comment by bcicen** [comment]
You don't need admin privileges in order to configure slackcat -- any member account should work without issue. Perhaps your account for this team is a "guest" account?

**Comment by zorro1992** [comment]
Well I am really not sure of that. But here is the below message what I get 
```
Apologies, but you are not authorized to install Slackcat.
If you’d like, you can message one of your admins and ask them to install this app.
```
I was able to create incoming web hocks and other stuff though .

**Comment by bcicen** [comment]
In that case, the admins have enabled "pre-approved" apps only. You can request the app be approved by them for usage by all team members here: https://slack.com/apps/A0HLKJ690-slackcat

**Comment by bcicen** [comment]
closing for now
