### ISSUE TITLE
Go vendoring

### ISSUE THREAD

**Issue by ilovezfs** [vektorlab/slackcat#50]
Would you be willing to start using a Go `vendor` directory or one of the other Go vendor systems so that we can avoid Go resource blocks in the Homebrew formula for `slackcat`?

Currently, the `slackcat` formula has five Go resource blocks. Checking whether there are updates for any, all, or none of these resources every time `slackcat` is upgraded is not ideal, but In the absence of Go vendoring, this is the only way we can ensure reproducible builds.

Some good choices are
https://github.com/golang/dep (`dep ensure`)
https://github.com/Masterminds/glide (`glide install`)
https://github.com/kardianos/govendor (`govendor sync`)
https://github.com/tools/godep (`godep restore`)

(Also as a side note, https://github.com/vektorlab/slackcat/blob/v1.3/main.go#L10 has moved from https://github.com/codegangsta/cli to https://github.com/urfave/cli.)

**Comment by bcicen** [comment]
Thanks @ilovezfs ; I'd be happy to move forward with vendored deps. Gopkg files have been added in https://github.com/vektorlab/slackcat/commit/1ed715826fb36b7ea74b74dc07ac5bcd635026fa

cli package import path has been updated as well.

**Comment by ilovezfs** [comment]
@bcicen thanks! We really appreciate it :)

**Comment by bcicen** [comment]
no problem :)
