### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by nickw108** [vektorlab/slackcat#56]
When I'm trying to run on a FreeBSD server, I get 

> bash: ./slackcat: cannot execute binary file: Exec format error

both with the slackcat-1.4-linux-amd64 and slackcat-1.4-linux-arm releases. As I don't have root access, I won't be able to compile either.

**Comment by bcicen** [comment]
FreeBSD build has been added to the [1.4 release page](https://github.com/vektorlab/slackcat/releases/tag/v1.4)

I don't readily have access to a freebsd platform to test this natively, so please do let me know if run into any issues

**Comment by nickw108** [comment]
Thank you so much, works just fine! 👍
