### ISSUE TITLE
Add streaming

### ISSUE THREAD

**Issue by bcicen** [vektorlab/slackcat#9]
Add streaming option to continuously flush piped input to Slack. Something like:
`tail -f /var/log/messages | slackcat --stream --channel my-channel`

**Comment by ytjohn** [comment]
Using the other slackcat, I do this:

`tail -F logfile | grep --line-buffered -v '^\s*$' | slackcat` 

https://github.com/skattyadz/slackcat/blob/master/slackcat.go#L192-L201



```
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		msg := SlackMsg{
			Channel:   cfg.Channel,
			Username:  cfg.Username,
			Parse:     "full",
			Text:      scanner.Text(),
			IconEmoji: cfg.IconEmoji,
		}
```

**Comment by bcicen** [comment]
Continuous streaming of input as preformatted messages has been added in the [latest release](https://github.com/vektorlab/slackcat/releases/tag/v0.8)
